version: '3.8'

services:
  nginx:
    # image: nginx:latest
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80" # public port
      - "443:443" # public port
    volumes:
      - ./conf:/etc/nginx/conf.d # configuration in default.conf
      - ./ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./ssl/letsencrypt:/etc/letsencrypt # Let's Encrypt SSL certificate
      - ./html:/var/www/html # static html web for example
      - ./log:/var/log/nginx/
    environment:
      - TZ=UTC
    networks:
      - web

networks:
  web:
    external: true
