services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    env_file:
      - .env
    networks:
      - web
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: ${HOST_NAME}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /home/nginxscale/nginx/ssl/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - SSL_TYPE=letsencrypt
      - TZ=UTC
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

networks:
  web:
    external: true