services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    external: true